### PR TITLE
digital clock ui snippet added

### PR DESCRIPTION
**Pull request by rohancs127**
This change adds a new ui snippet of digital clock to the repo.

### CODE REVIEW

**Review by Deveesh-Shetty — COMMENTED** [review]
Please update the Readme File as well, check `Contributing.md` for details
I will merge the PR after that

**Comment by rohancs127** [comment]
updated readme and snippets.json file

**Review by Deveesh-Shetty — APPROVED** [review]
LGTM

**Comment by Deveesh-Shetty** [comment]
Thanks for the PR!

Closes #24

**Pull request merged**
