### PR TITLE
Added FlipCard

### LINKED ISSUE #12: [UI] Build a Flipcard

### PR DESCRIPTION
**Pull request by MeetThakur**
closes #12 
Built a simple flipcard using html css which easy to customize

### CODE REVIEW

**Comment by MeetThakur** [comment]
should I add the codepen link in readme.md? @Deveesh-Shetty

**Review by Deveesh-Shetty — CHANGES_REQUESTED** [review]
The flip card looks good! Can you add this to the `Readme.md` file as well?

Copy the pattern from the previous projects and replace it with your content. I will merge it once it is done.

Feel free to ask any queries if you are stuck...
Thank you!

**Comment by Deveesh-Shetty** [comment]
> should I add the codepen link in readme.md? @Deveesh-Shetty
Yea please add it... I have requested that change.

**Comment by MeetThakur** [comment]
@Deveesh-Shetty I have added it to readme

**Review by Deveesh-Shetty — APPROVED** [review]
Looks good!
Thank you for contributing 🥳...

You can suggest more snippet ideas by raising issues about it, so more people can contribute!

**Pull request merged**
